// AUTO-GENERATED by scripts/build-media.mjs — do not edit by hand. Run `npm run media`.
/* eslint-disable */

export interface MediaAsset {
  /** intrinsic size of the largest rendition */
  w: number;
  h: number;
  /** available widths (px) — files: /media/<key>-<width>.avif|webp */
  widths: readonly number[];
  /** dominant color, used as placeholder background */
  color: string;
  /** CSS object-position focal point */
  focal: string;
  /** tiny blurred preview */
  lqip: string;
}

export const media = {
  "hero-contracting": {
    "w": 3200,
    "h": 2489,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#080808",
    "focal": "55% 62%",
    "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABwBQCdASoYABMAPt1gqU4opaOiMBgIARAbiWQAsQyTwXaOUHrI8FMgXsIbBiayupQs3kwAAP7AHYBR+XD6CS47UQvyCEb33VPzcbS8ocJFmk5WLe5aFspLaFff6M943fE3m+xL1cKPhWbqB5jwH/9TU+/J3lnhqLc1fTA4pIlyLuee3l4LWvMAmhrijutR2ORTJqw++ru0+Wf9perwwNS3zVHBPMV9Oh0/6rqhH4W1YrYQBxsIN27HfRQAAA=="
  },
  "hero-finishing": {
    "w": 3000,
    "h": 1688,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#080808",
    "focal": "50% 55%",
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABwBACdASoYAA4APt1apkyopSOiMAgBEBuJYwCdMoAC/B12WPjXfriRXb6sAAD+YTJczNKxowRAoeaJb4tcbrjuiwmTAWptzbN+aPTvdFU9i0XFNeyhSDdXTbgt25U+3XkW/RgkOIzqGe6D2VslJoIqpeT7xLQ1IRo3boRj3fMNtVdSW8T8zvlWOS8o72ml6thv59OBUWLw7sVmTAneIxrMkccDByrL1jwbNlq63ANyvRHCNgouggAA"
  },
  "hero-ceiling": {
    "w": 3200,
    "h": 2133,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#886848",
    "focal": "50% 40%",
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoYABAAPt1apkyopSOiMAgBEBuJYgCdMoC2AAYQrVPvr55cJIebWAAA/qLWsFBOFiN7WowhMu/wx6dtOAkR2EDU5g8QiJdcSKrxyjbamgPArpjjrlgeBTQxW9q7C1uR2KPjnY7MdL8f2ulZAoTh47OKlgwxsxMv/pMKNUmClbOcwsPerKAAAA=="
  },
  "hero-fitout": {
    "w": 3200,
    "h": 1800,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#b8a888",
    "focal": "58% 55%",
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoYAA0APt1cpkyopSOiMAgBEBuJQBOmUABfV3rz9xAoJ6VUJIAA/jvn+71f+h6WxGDjvuI0OwbE3PziNofY6gIWNPPVYrgNVRG9oCOkKb6muoAwjza78Z8YMDzV+GuOwobk690/0AEW9PsK/IC+ARtK2FiAw1QuVlwKN67h5MddHP/EwAA="
  },
  "about-structure": {
    "w": 2000,
    "h": 2667,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#d8d8d8",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRhwBAABXRUJQVlA4IBABAACwBQCdASoYACAAPt1eqU4opSOiMBgIARAbiWUAyy2MvD6GndU6vKDKpujGXUo/ahJwFr11S1gA/q0+uqLVnb86ePbncvBbJNIeFt7+P9UowoyntfMrbY5pBq6XUwOhL+EzjHEWSU7a16Gt2EDD8+Kk/Gf3pac3TyDB3BvBHiTIJBD1vTi6WYTTvlWTLGM6jwJ+ZzwzYIywKyzr9cHhdZmi/DISxdNDPd1QsELjLmbRIYVZfhmBCZT1uHCjrAYvHFweKJCr2B+n/rHudhlzsrSgvLOKsuZks40kJkwwsbbk89TH6nmA+8wjStiTM/+bM2hdDkDaVD3nM3wPq5YpSGlzgqbYY9wOYNhzJlW4wXYwAA=="
  },
  "about-space": {
    "w": 1935,
    "h": 1451,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#181818",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADwBACdASoYABIAPt1orVEopaQiqAgBEBuJZwDI1BEvDFCXfNRv+Y2spAfMbZaXHAAA/u7dauXpTcjlbyKK4XX9TVmvm58WH9GXtdJ2FeEvdPlNyBQdy9+He4sPZiqjVRj4Ct8j9pYIeJ0K1Gb0Hli/bY93oY6m+QlCX/t/o3K3OdZxjwRv77wRuSlkisvt/38nbpn22j0vo3aAAAA="
  },
  "svc-contracting": {
    "w": 2000,
    "h": 2500,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#082828",
    "focal": "50% 60%",
    "lqip": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADwBQCdASoYAB4APt1orVEopaQiqAgBEBuJbACdMuN1WQdAOLCwD6sRNhMIsDMB6mD9sbURbJbyQAD9+viHk6OE99QBZ9cISiIdFyP9ThNsZVtCqgt+J0hAzPQdc1oN0vKRtdyCtqfksrgJqmQ5XBqGRHt0WNr6R0FlbXrHiBtfxxD215O2w1JIXD8/4U455CEKye131VrtGl00WSfyRjZ8JjOtuCW9PFKLN0D94otpkwi9FAFywQJYUqG+5EMJqhpnZSzJSJmpHa9YhSuAAA=="
  },
  "svc-finishing": {
    "w": 1866,
    "h": 2333,
    "widths": [
      480,
      768,
      1080,
      1440,
      1866
    ],
    "color": "#583828",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABwBQCdASoYAB4APt1kqFAopaOiqAqpEBuJYwCsBbACfqpZPVaC2DX73bBpdQrvQ7C8GiEAAP7pqSK8AzOoR5OSOInIplpCXvFzTMujVvqTqtYTdJdEnstBlShsY0o91EM3wMs8rRiuQ4fKd1cnQxMjaUuD/YedzsE+fDrcDj78yiQPN0lOavQq8SI97/scJwSw/H96c79nD+AAoaBLC8BX+VGPu/zkz2ay13KY6gug9zQ0ZD+5Lc8CKfpTowwA"
  },
  "svc-ceiling": {
    "w": 2000,
    "h": 2500,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#382818",
    "focal": "50% 45%",
    "lqip": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAACQBgCdASoYAB4APt1ep04opSOiKA1REBuJZgCdMw5Bb9Hh/gddFiMrz2U7yN0G4nVIZtygHNAwUECvCxwAAP7bYYaGk/VtnpqRGhS83h5m1IeTyHykn7Fo8LZsP0j81YY9Gd7gobuBMh0/gdjDzk3dojgm0JVsew0JONm18zXyWeG/uMkKFudXLNgsICFdEmTbTiuyXNll3qBX1OwBWKjbrmfQfNniSpWuKV22eylNgO3sVZ7CiFjWwou3a7/4Cm3bj6b8Gygc0QmsbDJKzIKUcl+lH0AA"
  },
  "svc-fitout": {
    "w": 1302,
    "h": 1627,
    "widths": [
      480,
      768,
      1080,
      1302
    ],
    "color": "#080808",
    "focal": "45% 50%",
    "lqip": "data:image/webp;base64,UklGRvgAAABXRUJQVlA4IOwAAAAwBgCdASoYAB4APt1kqU+opaOiKAqpEBuJZQDGfy7AfFo4J/N8NZpSvAzzQaZLmLs10GeUoXQZEqwAAPxny9NUqPL3VCrfMZCqt1Uv1oPc9CNb1vT6CEXhj5ndHh4NfLkoXfgauUo/uqW6ljaOysRQ4aL3VoAbIX17dNx9anApzkhZj/zzZT1qzl6su9SPGt6EXd/f4AeQAD/7KRp+elOyfDDyTYFVNyhiITbTOhU6//fUhNJU9sres0vo13ES7KyxAVkD5ZotX53h8xteI+ePrsTHg/8S+nai6WxTA1NCGWHu7KVSiQjlX0hYAA=="
  },
  "prj-villa": {
    "w": 3000,
    "h": 1692,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#c8c8b8",
    "focal": "50% 55%",
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADwBACdASoYAA4APt1apkyopSOiMAgBEBuJbACdMoR4PzRh/gLZpB648gTOZEkMkwAA/tHhNIcOqqumEib1kOBzVxqXh57Gwp7dLps+m94hnr8lCPh1bHLwkWxyZLIptNrAFvd1sZT1RnG1JQaW8F95ObJjhNsfWgWiRdxwnJfOTRTP/ct0Ydf4ckB1gyrqdaBq8Hju3jE9JDG/zWm8wZasOj8JPlATtIP0lzjDNoxzdYAA"
  },
  "prj-hq": {
    "w": 2600,
    "h": 1950,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#c8a888",
    "focal": "50% 55%",
    "lqip": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAADwBACdASoYABIAPt1kqU+opSOiKAqpEBuJQBUk3kAgMWy7EJKDhnIftr664h5j/mAA/lv5GX//r19lffgvHkZHafh0LLJmxJFxj4dKn1Wb3l2GAVEE49IUHd3LYuW+wSl3CoU2iT0XLjNbVKDtswNB5aNF/KkRQE294HPoyrH28iPElL+djYcc2pTzBCUbx6ijpzRs11leI0jX/loDGAIrv5u7qY3UYIVmmnbfNyv08atGQ6+upQuTDgA="
  },
  "prj-restaurant": {
    "w": 2600,
    "h": 1457,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#080808",
    "focal": "42% 55%",
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoYAA0APt1apkyopSOiMAgBEBuJQBOgBDdM8THdf2mltw/4PrgA/uXv2XDur/GzsF4q7543sIg2IOL9t8s2ls0GfXL1r92JlDkO5DAncFrNugCzMx8OxbVm0jgIfYs8IP/gWZvIp7L9A1NIpVobFc+iYJRWMaiJfazjM7XJgAA="
  },
  "prj-residence": {
    "w": 2600,
    "h": 1560,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#a89878",
    "focal": "45% 55%",
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBACdASoYAA4APt1apkyopSOiMAgBEBuJQBOgA/C4rBORgIZc3V+vAAD87FqxtznleGoarh+jbo9RJdd0im0GfC8A44tBVKyZWiWGeconoeGk3A7VHjCaScyiiCJplp60CFE2c4WkD5WgvrnPLwRE4ODx8pHYMKa0HUvelf9AgVu+eUrsT4GS39BusrDEvqJQ0yOiXAJJuXFnjRmBM8AA"
  },
  "why-detail": {
    "w": 2000,
    "h": 1125,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#080808",
    "focal": "60% 50%",
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoYAA0APt1apkyopSOiMAgBEBuJYgCzh2gATzmQHM7H3G2561JAAPw3GjSjrgwRK8WGKcVN5KAR5hZXbdRO6MFUjy1wPBxW8EQT8jxayr9QUXZ6O2mxTZbfvAv/CW+uYS6y3xEkCtY8uQrvcSMTnzlGAAA="
  },
  "cta-riyadh": {
    "w": 2988,
    "h": 2241,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#180808",
    "focal": "55% 55%",
    "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAACQBQCdASoYABIAPt1gqE4opaOiMBgIARAbiWYArDL1NtAnMilJiYCVhp+c+lBdTR/SsjxFQAD+3gLgiH+FfryJQPv5xIaleOTwIlRmQj9V/ryIQ8obKkGz/ftrZX4PsKQBCjYKnmX5fGosfWKmhx0q6sSDXsXP5MDphTEd3H/MGPOHsWh4zLqL/Hdio2dSkM5LodycEVaHtWiyeBn6pUH/iugHFUjEPQFAf/21bG+qtQi4kAA="
  },
  "texture-slats": {
    "w": 2000,
    "h": 2500,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#080808",
    "focal": "50% 45%",
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACQBQCdASoYAB4APtFYqEyoJaSiMAwBABoJYgCdMw4/+CnHNhl9kDAlBasNULo/VTQytQQQAAD+6+DbtoXO+zpoVT0FyXrZukXiYoUgqQMcHODS0JU61D3snuwUxMc1UYrR1N+Cg/VB1L1SEchokKNnzoQ1CN3EjqIer2qnMW26kGKbAbabyVqI7qu7wAbdnxl6cNjoWUfZLW34z/m5wAAA"
  },
  "page-about": {
    "w": 2800,
    "h": 1867,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#181818",
    "focal": "50% 45%",
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoYABAAPt1apkyopSOiMAgBEBuJaQAAPwFnL8ZB6zhc7AAA/bcaVZ3wx9GBJLueQ6l0NkFJzXuVZl9+z/7g1pLnzo6ccB2F+ZHmJJPJ0lpJ8Kz4ohTjaD2nlmUTcg41LXlWLTagAAA="
  },
  "page-services": {
    "w": 2800,
    "h": 1867,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#080808",
    "focal": "45% 55%",
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAADQBACdASoYABAAPt1cpkyopSOiMAgBEBuJbAC7MoMjbEK5TMZOc01PUqaS8CdwUAD+9DKRr3rn4svadIoNwTTlU7acaFTqmUQdFpJK6cJB6KgOcSBSyobfkus9VseJ9dnxOXQhv/hj1QUlG/UWu/mNeI7DTHTQX6ogAI/c3Pt0TPyCuGjMvUhsGhkEbkpYp7KjJcvrRLde4gDCgAA="
  },
  "page-contact": {
    "w": 2800,
    "h": 1867,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#080808",
    "focal": "40% 48%",
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAwCdASoYABAAPt1ep00opSOiMAgBEBuJYzuAHWAHDGmFtAAA/vC2tkci9d9sZzUdV3CSJJ3kvepwyzVhFWm/OdDidRke7cGNAtVENx0vW6AXj7aYyLN7EAA="
  },
  "page-faq": {
    "w": 2800,
    "h": 1866,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#988858",
    "focal": "60% 50%",
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBACdASoYABAAPt1cp0yopSOiMAgBEBuJYgCdACPN6/LfOAHtByv3zAAA/mkT8qQgoTt8n/Kkqw1qBVnPqhove3X+k4efEGlDiAe8AsQCbCCa/bJ8LVEAUd0a5y9gsKXeQAAA"
  },
  "page-quote": {
    "w": 1406,
    "h": 1125,
    "widths": [
      480,
      768,
      1080,
      1406
    ],
    "color": "#d8d8d8",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADQBACdASoYABMAPt1kqU+opaOiKAqpEBuJZQCpFKnA07z1qQTvvT+PXi08iH6tAAD+wkpvyKO3BdbNL+6Mef2LbJvSb6ledRJdLvK6Ou66Phvu+w2U/ulXdpQNForNf0P77ZUzFBbEwM+jH1J2PCIEFn/mmbyF2gUE4CVxfwHyQdfC8paPXDqbSi1t3yOsO5aIjtSkmhvujf5M5ZDsX0MeAteFDg0pnGHK0+K0yYjIhcELzHwSGEQ/qgcwAA=="
  },
  "about-site": {
    "w": 1066,
    "h": 1333,
    "widths": [
      480,
      768,
      1066
    ],
    "color": "#787868",
    "focal": "50% 55%",
    "lqip": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAADQBQCdASoYAB4APtVYo0yoJSMiMAwBABqJQBdgZjt0cYenUPNFFmkjDkBB040QyDS8lZX/lh2QAP7a0QU/fMGQFyr0Xp0fU7QAIeBGzXHN9K8NLs9oTvMnAPhi54T5hFPy3duiM9k+74hqeUaPkwQwpQjBz0249dc2+dwnLiqXInUmJAsbSh3Q0vzfXhNWyB82rMOjdCPWmuw8U14yRnmQmIezl/IaagxVelbSG5Y5SnkSLYo7aDRwsNfFMwLfUPOeXFZjgkG6dBXiHBcjLsAdhk1HaqERwbiI7QgA"
  },
  "about-vision": {
    "w": 2800,
    "h": 1868,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#181818",
    "focal": "55% 45%",
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoYABAAPt1apkyopSOiMAgBEBuJaQAAWlvZDW14lyeez3IAAP6k2UvfZJWAS4+GAjQ/sYE0IlTp8BrxP3Sy72uK2531DJbNgy22VNSQY/BwG3lfAAA="
  },
  "about-quality": {
    "w": 1066,
    "h": 1333,
    "widths": [
      480,
      768,
      1066
    ],
    "color": "#583818",
    "focal": "60% 50%",
    "lqip": "data:image/webp;base64,UklGRvoAAABXRUJQVlA4IO4AAADQBQCdASoYAB4APt1irE8opSSiKAqpEBuJZACdMoAlzgwLc3P67KjLRJ/JYCKb4eDwvRMF0qHAAP6Jfs/p76KzKz+0KzXNI67Iwr8tPOEbdmM3NSIcWSc1Ek+WWCd1rsB7wzFH+Ko7KTefKSuTTpjNIPDQhcOFlYw/WyczEJbiYWOQd8CAPgPVuSDugKtHwHxq8timDqf8VkqNaqmRIw27rQK1Ld5TI3ixTngIjOoiNkOxIW7y3pLepXbtc9OgMFiSA76aHy5ty6l+Ftxxrz4DgHTpieqRhX8HpvNjKqii0tDbsQAJNuay0MfAgAAA"
  },
  "detail-joinery": {
    "w": 2000,
    "h": 2667,
    "widths": [
      400,
      640,
      960,
      1280
    ],
    "color": "#584838",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwBACdASoYACAAPt1krE8opaSiKAqpEBuJZwC/7DDm70E9SvcxcqJyM3z88VJuUoAA/tpycba4kO7HPD+r6Z2TvS8XqZWa7O9xCUOJf+dZn00RXs3rLKSf2ttGHixwMg4bOyxppIqzlz9FUg3nIAAA"
  },
  "detail-stone": {
    "w": 2000,
    "h": 2667,
    "widths": [
      400,
      640,
      960,
      1280
    ],
    "color": "#e8e8e8",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoYACAAPt1apUyopSOiMAgBEBuJYwC/OBnyx0pFX+jqE3GeAAD+d2DCpjM5u3dxd+2efgrtXeCSr2B04h2BKah31DQ2I0/B9pZ8LHWEldgik6edI2gUwMnfmEfpEmkl6L2L2t6fMWLcdC/q6XNrG/u3Xo1z9+KKZZFC1iQoPpyWFAEsaX9RkYvtlAkOLKJtOmXecAAA"
  },
  "detail-lighting": {
    "w": 2000,
    "h": 2667,
    "widths": [
      400,
      640,
      960,
      1280
    ],
    "color": "#a87848",
    "focal": "50% 45%",
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBQCdASoYACAAPs1SoUynpKMiN/qoAPAZiWQAqRUgAfe8qM+wQSl6ZTg0+UOJmo8XmuLAAMiMONjgZzv7XWnobXPstgI7H7jMaIMBke+Hd9/pU+6stRDjU+l2q3txGGfUkiyvDe4/BilKxWjoST2Ljg7CnERxnXbY55LvNvEXrxywJCa00NtuFnbePspqxsz+myC8XGxR6ARt0EyAAA=="
  },
  "detail-plaster": {
    "w": 2000,
    "h": 2667,
    "widths": [
      400,
      640,
      960,
      1280
    ],
    "color": "#384848",
    "focal": "50% 50%",
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQBACdASoYACAAPt1cpky/pSOiMAgD8BuJZwDImBHSiZtIOKZLErzwAAD3BIG4pEzF/TNRdXBDp7zk3hn0TSze0nu0JVg6xKtRmYb2tmwPknfzSTuOAA=="
  },
  "page-projects": {
    "w": 2800,
    "h": 1867,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#b8a898",
    "focal": "50% 58%",
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoYABAAPt1cpkyopSOiMAgBEBuJQBOgA3FxUatY8hoefS4AAPHhA3N9YtohYhBNHAIN2kqHBfK2kFqxHbMyVYlfXdJQeMP9MjNDop89j4tLQfRm2CETAsuWfvfucwNbM6WdyUmP9N836xH44d+UqRpSQtEjU8F52PiBwarCwIB0jKG0qCfHPuPe6Zw4DkAA"
  },
  "prj-office": {
    "w": 2800,
    "h": 1867,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#080808",
    "focal": "45% 55%",
    "lqip": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABQBACdASoYABAAPt1apkyopSOiMAgBEBuJQBadBEAMB1iPUgwbfI+TqF7AAP7qN/9xjU+Q8aimL/o3+vUXo9eVQGNicrtJ/x5OnyDHGgjCY/fsE8yaj2d42OyrMeuQ/WatumJshYCD4PzX0IIBfDhudB0t+mULiJs67P7IGsWUDSs19DWND0yc99/Ng4Y6n30EpNIurwNhTXWIsKpHJkljQD8TQy4siI1UJ+6Or1GUQcnURWQAAA=="
  },
  "prj-retail": {
    "w": 2800,
    "h": 1867,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#988878",
    "focal": "55% 50%",
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYABAAPt1apkyopSOiMAgBEBuJYwCdMoAlthbyuPEgftYRNyQfAAD+5ErIiWGzhci5tAPOiQJAijaKM/mO1gTy1aGncMXdBgmAcFqh3oEBeATAoNArYwS9ZqWkezPpb5NyrlGKVzrshC+iUTpU2Mk7sguAEw7q6ow+R4GuR0AAAA=="
  },
  "prj-majlis": {
    "w": 2800,
    "h": 1867,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#b8a898",
    "focal": "50% 60%",
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoYABAAPt1cpkyopSOiMAgBEBuJQBOgA3FxUatY8hoefS4AAPHhA3N9YtohYhBNHAIN2kqHBfK2kFqxHbMyVYlfXdJQeMP9MjNDop89j4tLQfRm2CETAsuWfvfucwNbM6WdyUmP9N836xH44d+UqRpSQtEjU8F52PiBwarCwIB0jKG0qCfHPuPe6Zw4DkAA"
  },
  "prj-cafe": {
    "w": 2800,
    "h": 1575,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#c8c8c8",
    "focal": "40% 55%",
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBACdASoYAA0APt1apkyopSOiMAgBEBuJYgCdMoADgP/hhHi5HFhC4qqucAD+0+XApNJevD2dfeEfrFx4wFNDKdNdV71TIhwMJJhQCaUu1qVHSNIRO85PFqQ+T/1gx4VK1LsX7vnVhnbZ0zoznVvycsyHEV+k0PUrC3hwMly+GT83GeAxf0jv2HcgpWTnuAA="
  },
  "prj-apartment": {
    "w": 2800,
    "h": 1575,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#080808",
    "focal": "45% 50%",
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoYAA0APt1cpkyopSOiMAgBEBuJYgCdMoACasYHgE6OXGlGAAD7pYNTPkwAwZjww2ZbKOrHnvj6NP+LMxE+M9jO/B0JrkQ1aooGMgR4e6YLinajD5ka5sQbC3jKNl1wuzlcdgffmgwqVsDDxgmp5nESjEDV2Cd4rDH8IvsS+QgLMdyUBIT5tl20k45WHp1g1D4YLjQ4gAA="
  },
  "prj-structure": {
    "w": 2800,
    "h": 1867,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920
    ],
    "color": "#080808",
    "focal": "62% 58%",
    "lqip": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAQBQCdASoYABAAPt1apkyopSOiMAgBEBuJbACdMoR3IsCrAW/+A8rjjZyi+1vdMpQAAP7sPZ1ocElq2ASMBHVYVUv3FogxAr9v98Lyctu2r7kxPvMN4RV+vHAKk7Vq2pIruvPTjCM4hU3EnpBySDsCCMzD0+r0fdBjtTWuq+N/yR+C5PqUrEtXO1Jo+X97Jx91bgsT5MVDcIWBSj908A3eLy/wpU5M+uDOvsjajria13YBed6fOIgA"
  },
  "prj-hall": {
    "w": 2800,
    "h": 1867,
    "widths": [
      640,
      960,
      1280,
      1920,
      2560
    ],
    "color": "#181808",
    "focal": "50% 45%",
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwAwCdASoYABAAPt1apkyopSOiMAgBEBuJQBOmUABpekY+7jP0oADLT6MJSRc9LZ9Zobw6qO0ptJM4f7w1uRjxJG0zPFbNKB58JDc4vE0ArvmurlGYumuAcE5rgPMIpzMj1SPioxkNBe3x9/coH9Ax78Gw+36O4TrmDS+xHSa5vhJO3vhUtjwzB+ocbnoUAAA="
  },
  "svc-ceiling-2": {
    "w": 1582,
    "h": 1978,
    "widths": [
      480,
      768,
      1080,
      1440,
      1582
    ],
    "color": "#382818",
    "focal": "55% 45%",
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwBQCdASoYAB4APt1YpkyopKOiMBgMARAbiWQAuzM0P3ckgdVBWM8+L0k3aU7CogZUrNAB38YA/u5+7U2hZDYHcRIrrR2IKqSxfkQCiU2qlCTYpAdyPL/BDYOdynTqcFde5GnY8DFWqliR48tfiAq+0kHqU3hGQX1rZiNfRBqAG6H6BhV1059GSjRjwkKIWBkkWcFD7SDRjAwV2rgAAA=="
  }
} as const satisfies Record<string, MediaAsset>;

export type MediaKey = keyof typeof media;

export const brandAssets = {
  "lockup-on-dark": {
    "w": 640,
    "h": 117
  },
  "lockup-on-light": {
    "w": 640,
    "h": 117
  },
  "logo-on-dark": {
    "w": 560,
    "h": 487
  },
  "logo-on-light": {
    "w": 560,
    "h": 487
  },
  "symbol-on-dark": {
    "w": 360,
    "h": 280
  },
  "symbol-on-light": {
    "w": 360,
    "h": 280
  }
} as const;
